language: php
dist: trusty
git:
  depth: 3  
cache:
  directories:
    - ~/.composer/cache/
jobs:
  include:
# PHP Linting
    - stage: PHP Linting
      php: 7.3
      name: PHP 7.3
      before_install:
        - phpenv config-rm xdebug.ini || true
        - mkdir ../tools && composer init --name=putg/tools --working-dir=../tools
        - composer require jakub-onderka/php-parallel-lint:^1 --working-dir=../tools
      install: true
      script:
        - ../tools/vendor/bin/parallel-lint --exclude vendor .
    - stage: PHP Linting
      php: 7.2
      name: PHP 7.2
      before_install:
        - phpenv config-rm xdebug.ini || true
        - mkdir ../tools && composer init --name=putg/tools --working-dir=../tools
        - composer require jakub-onderka/php-parallel-lint:^1 --working-dir=../tools
      install: true
      script:
        - ../tools/vendor/bin/parallel-lint --exclude vendor .
# Unit Tests
    - stage: Test
      php: 7.3
      name: PHP 7.3
      before_install:
        - mkdir ../tools && composer init --name=putg/tools --working-dir=../tools
        - composer require codacy/coverage:dev-master --working-dir=../tools
      install:
        - composer update
      script:
        - vendor/bin/phpunit --testdox --coverage-text --coverage-clover clover.xml
      after_success:
        - ../tools/vendor/bin/codacycoverage clover clover.xml
    - stage: Test
      php: 7.2
      name: PHP 7.2
      before_install:
        - phpenv config-rm xdebug.ini || true
      install:
        - composer update
      script:
        - vendor/bin/phpunit --testdox
# Static Code Analysis
    - stage: Static Code Analysis
      php: 7.3
      name: "PHP Codesniffer: PSR12"
      before_install:
        - phpenv config-rm xdebug.ini || true
        - mkdir ../tools && composer init --name=putg/tools --working-dir=../tools
        - composer require squizlabs/php_codesniffer:^3.2.2 --working-dir=../tools
      install: true
      script:
        - ../tools/vendor/bin/phpcs -p --standard=PSR12 .
# Pre-Tag
    - stage: Pre-Tag
      php: 7.3
      name: PHPmetrics
      before_install:
        - phpenv config-rm xdebug.ini || true
        - mkdir ../tools && composer init --name=putg/tools --working-dir=../tools
        - composer require phpmetrics/phpmetrics:^2.4.1 --working-dir=../tools
      install:
        - composer update
      script:
        - php ../tools/vendor/bin/phpmetrics . --exclude=vendor
    - stage: Pre-Tag
      php: 7.3
      name: PHP Semver Checker
      before_install:
        - phpenv config-rm xdebug.ini || true
        - mkdir ../tools && composer init --name=putg/tools --working-dir=../tools
        - composer create-project tomzx/php-semver-checker-git:^0.7 --working-dir=../tools
      install: composer update
      script:
        - ../tools/php-semver-checker-git/bin/php-semver-checker-git suggest --allow-detached --details --include-before=src --include-after=src
