language: php
dist: trusty
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
matrix:
  include:
    - php: "5.3"
      dist: precise
git:
  depth: 3
before_script:
# no need to provide coverage more than once and no need for the speedbump otherwise
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require codacy/coverage:dev-master --no-update ; fi
# no need to test formatting more than once and php_codesniffer does not work with older php
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer require squizlabs/php_codesniffer:^3.1 --no-update ; fi
# actually installing
  - composer update
script:
# unit tests
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then vendor/bin/phpunit --testdox --bootstrap vendor/autoload.php test/ ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then phpunit --testdox --coverage-text --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php --whitelist src/ test/ ; fi
# check standards
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then vendor/bin/phpcs -p --standard=PSR2 src test check-config.php ; fi
# self-check config
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then php check-config.php ; fi
after_success:
# upload coverage
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php vendor/bin/codacycoverage clover build/logs/clover.xml ; fi
